"""Critic trial: generate a consumer with N fields in groups of 32 plus N/10 commands.

python tests/review/critic/gen_scaling.py N out.cpp
The generated file is a build input; write it under build/review-critic/.
Field kinds rotate through f32 read-only, u16 read-only, f32 writable with limits,
enum writable, u32 read-only, bool read-only, so the table resembles a metering device.
"""
import sys

n = int(sys.argv[1])
out = sys.argv[2]
per_group = 32
groups = (n + per_group - 1) // per_group
lines = [
    "// Generated by tests/review/critic/gen_scaling.py; do not edit.",
    '#include "Telemetry.h"',
    "#ifdef CRITIC_JSON",
    '#include "serialization/TelemetryCommandJson.h"',
    '#include "serialization/TelemetryJson.h"',
    "#endif",
    "#include <cstdint>",
    "namespace scale {",
    "using telemetry::WriteResult; using telemetry::CommandResult;",
    "enum class Mode : std::uint8_t { Off, Auto, Manual, Test };",
    "struct Block {",
    "  float f[8] = {}; std::uint16_t u[4] = {}; std::uint32_t c = 0; bool b = false; Mode m = Mode::Auto;",
]
for k in range(8):
    lines.append(f"  float rf{k}() const noexcept {{ return f[{k}]; }}")
    lines.append(f"  WriteResult wf{k}(float v) noexcept {{ f[{k}] = v; return WriteResult::Applied; }}")
for k in range(4):
    lines.append(f"  std::uint16_t ru{k}() const noexcept {{ return u[{k}]; }}")
lines += [
    "  std::uint32_t rc() const noexcept { return c; }",
    "  bool rb() const noexcept { return b; }",
    "  Mode rm() const noexcept { return m; }",
    "  WriteResult wm(Mode v) noexcept { m = v; return WriteResult::Applied; }",
    "  CommandResult reset() noexcept { c = 0; return CommandResult::Executed; }",
    "  CommandResult set(float v, Mode mode) noexcept { f[0] = v; m = mode; return CommandResult::Executed; }",
    "};",
    f"Block blocks[{groups}];",
]
count = 0
for g in range(groups):
    rows = []
    for i in range(per_group):
        if count >= n:
            break
        kind = count % 6
        name = f'"g{g}f{i}"'
        if kind == 0:
            rows.append(f'telemetry::field<&Block::rf{i % 8}>({name}, "V", blocks[{g}])')
        elif kind == 1:
            rows.append(f'telemetry::field<&Block::ru{i % 4}>({name}, "", blocks[{g}])')
        elif kind == 2:
            rows.append(f'telemetry::field<&Block::rf{i % 8}, &Block::wf{i % 8}>({name}, "A", blocks[{g}], '
                        f'telemetry::limits(1.0f, 0.0f, 100.0f)).withFlags(telemetry::FieldFlag::Persistent)')
        elif kind == 3:
            rows.append(f'telemetry::field<&Block::rm, &Block::wm>({name}, "", blocks[{g}], telemetry::limits(Mode::Auto))')
        elif kind == 4:
            rows.append(f'telemetry::field<&Block::rc>({name}, "", blocks[{g}])')
        else:
            rows.append(f'telemetry::field<&Block::rb>({name}, "", blocks[{g}])')
        count += 1
    lines.append(f"inline constexpr telemetry::FieldTable t{g}{{")
    lines.append(",\n".join("  " + r for r in rows))
    lines.append("};")
    cmds = []
    for i in range(max(1, len(rows) // 10)):
        if i % 2 == 0:
            cmds.append(f'telemetry::command<&Block::reset>("g{g}c{i}", blocks[{g}])')
        else:
            cmds.append(f'telemetry::command<&Block::set>("g{g}c{i}", blocks[{g}], '
                        f'telemetry::arg<0>("v", "V", 1.0f, 0.0f, 10.0f), telemetry::arg<1>("m", "", Mode::Auto))')
    lines.append(f"inline constexpr telemetry::CommandTable k{g}{{")
    lines.append(",\n".join("  " + r for r in cmds))
    lines.append("};")
lines.append("inline constexpr telemetry::FieldCatalogTable fields{")
lines.append(",\n".join(f'  telemetry::group("g{g}", t{g})' for g in range(groups)))
lines.append("};")
lines.append("inline constexpr telemetry::CommandCatalogTable commands{")
lines.append(",\n".join(f'  telemetry::group("g{g}", k{g})' for g in range(groups)))
lines.append("};")
lines += [
    "} // namespace scale",
    "extern \"C\" unsigned scaleRead(unsigned id) noexcept {",
    "  constexpr auto index = scale::fields.index();",
    "  auto v = index.read<float>(id); return v ? static_cast<unsigned>(*v) : 0u; }",
    "extern \"C\" int scaleWrite(unsigned id, float v) noexcept {",
    "  constexpr auto index = scale::fields.index();",
    "  return static_cast<int>(index.write(id, v)); }",
    "extern \"C\" int scaleExec(unsigned id, const telemetry::Scalar* a, unsigned n) noexcept {",
    "  constexpr auto index = scale::commands.index();",
    "  return static_cast<int>(index.execute(id, a, n)); }",
    "#ifdef CRITIC_JSON",
    "extern \"C\" unsigned scaleJson(char* out, unsigned size) noexcept {",
    "  constexpr auto index = scale::fields.index();",
    "  constexpr auto cindex = scale::commands.index();",
    "  return static_cast<unsigned>(telemetry::writeSchema(index, out, size) + telemetry::writeValues(index, out, size)",
    "       + telemetry::writeSchema(cindex, out, size)); }",
    "#endif",
]
with open(out, "w", encoding="utf-8") as f:
    f.write("\n".join(lines) + "\n")
print(f"{n} fields, {groups} groups -> {out}")
