#!/usr/bin/env python3
"""Rebuild the appendix of All-Conclusions.md from the exported transcripts.

For each of the ten agents, in the order of export_transcripts.ROLES, the appendix
holds, verbatim: the brief, every message the agent received while working, every
text the agent wrote, and its final report. The critic's section also carries the
helper files it wrote after its report (tests/review/critic/helpers); their part (c)
lists its corrections to that report. Reasoning, tool calls and tool results are
left out; they are in transcripts/<slug>.md.

Everything from the first line starting with "## APPENDIX" is replaced, so the
script can be re-run after a new export. Before writing, it checks that every
copied text occurs in the output unchanged. It prints only counts.

Usage:
    python build_all_agents.py
"""
import pathlib
import sys

from export_transcripts import ROLES, fence, handback_text, load

HERE = pathlib.Path(__file__).resolve().parent
TARGET = HERE / "All-Conclusions.md"
RAW = HERE / "transcripts" / "raw"
HELPERS = HERE.parent.parent / "tests" / "review" / "critic" / "helpers"
MARKER = "## APPENDIX"


def user_text(content):
    """A user message as text: a plain string, or a list of text blocks with no tool results."""
    if isinstance(content, str):
        return content
    blocks = content or []
    if not blocks or any(block.get("type") == "tool_result" for block in blocks):
        return None
    texts = [block.get("text", "") for block in blocks if block.get("type") == "text"]
    return "\n".join(texts) if texts else None


def agent_parts(records):
    brief, later, texts, report = None, [], [], None
    for record in records:
        stamp = record.get("timestamp", "")
        content = (record.get("message") or {}).get("content")
        if record.get("type") == "user":
            text = user_text(content)
            if text is None:
                continue
            if brief is None:
                brief = text
            else:
                later.append((stamp, text))
        elif record.get("type") == "assistant":
            for block in content or []:
                if block.get("type") == "text":
                    texts.append((stamp, block.get("text", "")))
                found = handback_text(block)
                if found is not None:
                    report = found
    return brief, later, texts, report


def main():
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")
    lines = TARGET.read_text(encoding="utf-8").split("\n")
    cut = next((i for i, line in enumerate(lines) if line.startswith(MARKER)), len(lines))
    head = "\n".join(lines[:cut]).rstrip()
    if head.endswith("---"):
        head = head[:-3].rstrip()

    out = [f"{MARKER}: all {len(ROLES)} agents, verbatim", "",
           "Generated by build_all_agents.py from transcripts/raw/*.jsonl. Nothing here is edited or "
           "shortened. Per agent: brief, messages received while working, every text it wrote in order, "
           "final report. Reasoning, tool calls and tool results are in transcripts/<slug>.md.", ""]
    copied = []
    for number, (_, slug, role) in enumerate(ROLES, 1):
        brief, later, texts, report = agent_parts(load(RAW / f"{slug}.jsonl"))
        out += [f"## Agent {number} of {len(ROLES)}: {role}", "",
                f"Source: transcripts/raw/{slug}.jsonl; full transcript: transcripts/{slug}.md.", "",
                "### Brief (verbatim)", "", fence(brief or "(no brief found)"), ""]
        for stamp, text in later:
            out += [f"### Message received while working, {stamp} (verbatim)", "", fence(text), ""]
        out += [f"### Every text the agent wrote, in order ({len(texts)})", ""]
        for stamp, text in texts:
            out += [f"#### {stamp}", "", fence(text), ""]
        out += ["### Final report (verbatim)", "", report or "(no final report found)", ""]
        copied += [brief, report] + [text for _, text in later + texts]

        helper_files = sorted(HELPERS.glob("*.md")) if slug == "07-critic" else []
        if helper_files:
            out += ["### Files the critic wrote after its final report (verbatim)", "",
                    "Part (c) of each file lists what the critic corrected in its own report; "
                    "those corrections are not in the final report above.", ""]
            for path in helper_files:
                text = path.read_text(encoding="utf-8")
                out += [f"#### tests/review/critic/helpers/{path.name}", "", text, ""]
                copied.append(text)
        print(f"{number:2} {slug:45} brief {len(brief or ''):6}  later {len(later):2}  "
              f"texts {len(texts):3}  report {len(report or ''):6}  helper files {len(helper_files)}")

    result = head + "\n\n---\n\n" + "\n".join(out)
    missing = sum(1 for text in copied if text and text not in result)
    if missing:
        print(f"ERROR: {missing} copied texts are not in the output unchanged; nothing written")
        return 1
    TARGET.write_text(result, encoding="utf-8")
    reread = TARGET.read_text(encoding="utf-8")
    missing = sum(1 for text in copied if text and text not in reread)
    print(f"written {TARGET.name}: {len(reread):,} chars; copied texts checked {len(copied)}, "
          f"missing after write {missing}; appendix markers {reread.count(chr(10) + MARKER)}")
    return 1 if missing else 0


if __name__ == "__main__":
    sys.exit(main())
