// Frozen ABI 7 tuple from f1cfbd8. Identical pointer offsets do not imply identical semantics.
#pragma once
#include "abi/TelemetryAbi.h"
static_assert(telemetry::telemetryAbiVersion == 8, "Review legacy ABI fixtures");
namespace telemetry::detail {
using LegacyAbi7Tag = AbiTag<
    7,
    cacheLineBytes,
    sizeof(void*),
    sizeof(Scalar),
    alignof(Scalar),
    Scalar::abiStorageOffset(), Scalar::abiStorageSize(), Scalar::abiStorageAlign(),
    sizeof(Getter),
    alignof(Getter),
    Getter::abiPayloadOffset(), Getter::abiInvokeOffset(),
    Getter::abiPayloadSize(), Getter::abiPayloadAlign(),
    sizeof(Setter),
    alignof(Setter),
    Setter::abiPayloadOffset(), Setter::abiInvokeOffset(),
    Setter::abiPayloadSize(), Setter::abiPayloadAlign(),
    sizeof(FieldType),
    alignof(FieldType),
    FieldType::abiValueTypeOffset(), FieldType::abiRestrictedOffset(),
    FieldType::abiBoundsOffset(), FieldType::abiInitialOffset(),
    FieldType::abiEnumOpsOffset(), FieldType::abiBoundsSize(), FieldType::abiBoundsAlign(),
    sizeof(Field),
    alignof(Field),
    offsetof(Field, get),
    offsetof(Field, readType),
    offsetof(Field, name),
    offsetof(Field, unit),
    offsetof(Field, set),
    offsetof(Field, declaredType),
    Field::abiFlagsOffset(), sizeof(FieldFlags), alignof(FieldFlags),
    sizeof(Catalog),
    alignof(Catalog),
    offsetof(Catalog, name),
    offsetof(Catalog, fields),
    offsetof(Catalog, count),
    sizeof(CatalogIndex), alignof(CatalogIndex),
    CatalogIndex::abiCatalogsOffset(), CatalogIndex::abiCountOffset(),
    sizeof(Command), alignof(Command),
    offsetof(Command, name),
    offsetof(Command, owner), offsetof(Command, metadata),
    offsetof(Command, invoke), offsetof(Command, params),
    sizeof(CommandParam), alignof(CommandParam),
    offsetof(CommandParam, index), offsetof(CommandParam, name),
    offsetof(CommandParam, unit), offsetof(CommandParam, type),
    sizeof(CommandIndex), alignof(CommandIndex),
    CommandIndex::abiCommandsOffset(), CommandIndex::abiCountOffset(),
    sizeof(CommandCatalog), alignof(CommandCatalog),
    offsetof(CommandCatalog, name),
    offsetof(CommandCatalog, commands), offsetof(CommandCatalog, count),
    sizeof(CommandCatalogIndex), alignof(CommandCatalogIndex),
    CommandCatalogIndex::abiCatalogsOffset(), CommandCatalogIndex::abiCountOffset()>;
}
